### ISSUE TITLE
SockJS connections do not seem to close properly

### ISSUE THREAD

**Issue by henrikjn** [sockjs/sockjs-node#153] opened 2014-04-02 18:29 UTC
I'm using HAProxy in front of my SockJS servers and am having troubles with SockJS connections not seeming to close properly.

My NodeJS code:

```
var sockjsSockets = {};


/**
 * SockJS Server
 */
var echo = sockjs.createServer({
    log: function (severity, message) {
        // Skip logging
    },
    disconnect_delay: 20
});
echo.on('connection', function (conn) {

    // Identify this connection
    sockjsSockets[conn.id] = conn;

    conn.on('data', function (message) {

        // Write...

    });
    conn.on('close', function () {

        try {
            delete sockjsSockets[conn.id];

            conn.close(); 
        } catch (er) {
            console.log("EXCEPTION CLOSE SOCKJS ::::::::>>>>>>> " + er.stack);
        }
    });
});
```

The sockjsSockets count can for example show: 400 But HAProxy is showing 3000ish current connections to that NodeJS instance, this is after a few hours of running.

If i restart the SockJS server it goes back to normal again.

Any ideas what could be wrong?

Edit

Here is my HAProxy config

```
global
      maxconn     400000
      ulimit-n    800019
      nbproc      1
      debug
      daemon
      log         127.0.0.1   local0 notice

  defaults
      mode        http
      option      httplog
      log         global
      stats       enable
      stats       refresh 60s
      stats uri   /stats
      maxconn     32768


  frontend  secured
      timeout     client 86400000

      mode http
      timeout client 120s

      option httpclose
      option forwardfor

      bind        0.0.0.0:443 ssl crt /etc/nginx/ssl/ssl-bundle.pem ciphers RC4-SHA:AES128-SHA:AES:!ADH:!aNULL:!DH:!EDH:!eNULL


      acl is_sockjs path_beg /echo /broadcast /close # this is sockjs
      use_backend sockjs if is_sockjs
```

**Comment by brycekahle** [comment] 2018-09-24 20:02
Duplicate of #171 which was fixed in `0.3.13`

**Closed by brycekahle** 2018-09-24 20:02 UTC
